### ISSUE TITLE
code missing?

### ISSUE THREAD

**Issue by ltalirz** [SenjaBarthel/TuTraSt#1]
Hi @SenjaBarthel 

Sorry for not having checked the content of the repository before - but there doesn't seem to be any code in this repository, including the release on zenodo. Could you please add it?

Data linked to from the Materials Cloud Archive should be relevant to computational materials science, and we would like to avoid links to data like

> Fuhrer g guys hugs just funny fresh office dubs dark 

Thanks!

**Comment by SenjaBarthel** [comment]
Hi Leopold,

I am sorry for people chasing you. 
You know that we were behind the publication time with making the code available. But we are going to put it on the linked page asap. If there is any action required in the meantime please let me know.

Best,
Senja

**Comment by SenjaBarthel** [comment]
Alright!

References & keywords are two fields that can be edited in published records, so for the next time I would suggest to simply add the reference to zenodo later
(we can even make a new version for it if you like).
I guess my initial advice was not clear, so no worries - we are all learning how to do this ;-)

Best,
Leo
